"""
Retail customer event producer.

Publishes ~10 JSON events/second to the 'customer-events' Kafka topic.
10 % of events carry a timestamp 30–60 seconds in the past to simulate
late arrivals — the pattern that makes watermarks necessary.

Usage:
    pip install confluent-kafka faker
    python producer/produce_events.py
    # or override the broker address:
    KAFKA_BOOTSTRAP_SERVERS=localhost:9092 python producer/produce_events.py
"""

from __future__ import annotations

import json
import logging
import os
import random
import signal
import time
import uuid
from datetime import datetime, timedelta, timezone

from faker import Faker
from confluent_kafka import Producer
from confluent_kafka.admin import AdminClient, NewTopic

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(levelname)-8s  %(message)s",
)
log = logging.getLogger(__name__)

TOPIC = "customer-events"
EVENTS_PER_SECOND = 10
LATE_ARRIVAL_PROBABILITY = 0.10
LATE_ARRIVAL_SECONDS_MIN = 30
LATE_ARRIVAL_SECONDS_MAX = 60

# Stable pool of 20 customer IDs so window aggregations are non-trivial
# (multiple events per customer per 5-minute window).
fake = Faker()
Faker.seed(42)
CUSTOMER_IDS = [f"cust_{fake.unique.bothify(text='??##??').upper()}" for _ in range(20)]

EVENT_TYPES = ["click", "purchase", "return"]
EVENT_TYPE_WEIGHTS = [0.60, 0.30, 0.10]  # most events are clicks


def _create_topic_if_missing(bootstrap_servers: str) -> None:
    admin = AdminClient({"bootstrap.servers": bootstrap_servers})
    existing = admin.list_topics(timeout=5).topics
    if TOPIC not in existing:
        log.info("Creating topic '%s'", TOPIC)
        futures = admin.create_topics([NewTopic(TOPIC, num_partitions=4, replication_factor=1)])
        for topic, future in futures.items():
            try:
                future.result()
                log.info("Topic '%s' created.", topic)
            except Exception as exc:
                log.warning("Could not create topic '%s': %s", topic, exc)


def _generate_event() -> dict:
    """
    Build a single customer event.

    Late arrivals are generated by subtracting a random delay from now.
    The Flink watermark (configured at 30 s out-of-orderness) will absorb
    these late events and still include them in the correct window,
    provided the delay is ≤ 30 s.  Events delayed 31–60 s will arrive
    after the window closes and be counted as late by Flink — intentional,
    to demonstrate what out-of-orderness looks like in practice.
    """
    now = datetime.now(timezone.utc)

    if random.random() < LATE_ARRIVAL_PROBABILITY:
        delay = timedelta(
            seconds=random.randint(LATE_ARRIVAL_SECONDS_MIN, LATE_ARRIVAL_SECONDS_MAX)
        )
        event_time = now - delay
    else:
        event_time = now

    event_type = random.choices(EVENT_TYPES, weights=EVENT_TYPE_WEIGHTS, k=1)[0]

    if event_type == "click":
        amount = 0.0
    elif event_type == "purchase":
        amount = round(random.uniform(5.0, 499.99), 2)
    else:  # return
        # Negative amount: a return reduces net spend for the customer
        amount = round(-random.uniform(5.0, 199.99), 2)

    return {
        "event_id": str(uuid.uuid4()),
        "customer_id": random.choice(CUSTOMER_IDS),
        "event_type": event_type,
        "amount": amount,
        "event_timestamp": event_time.isoformat(),
    }


def _delivery_report(err, msg) -> None:
    if err:
        log.error("Delivery failed for message %s: %s", msg.key(), err)


def run(bootstrap_servers: str) -> None:
    _create_topic_if_missing(bootstrap_servers)

    producer = Producer({
        "bootstrap.servers": bootstrap_servers,
        "linger.ms": 5,       # small batching for throughput
        "acks": "1",
    })

    interval = 1.0 / EVENTS_PER_SECOND
    produced = 0
    running = True

    def _shutdown(signum, frame):
        nonlocal running
        log.info("Shutting down — flushing %d in-flight messages…", produced)
        running = False

    signal.signal(signal.SIGINT, _shutdown)
    signal.signal(signal.SIGTERM, _shutdown)

    log.info(
        "Producing to %s/%s at ~%d events/sec  (%.0f%% late arrivals)",
        bootstrap_servers,
        TOPIC,
        EVENTS_PER_SECOND,
        LATE_ARRIVAL_PROBABILITY * 100,
    )

    while running:
        start = time.monotonic()

        event = _generate_event()
        payload = json.dumps(event).encode("utf-8")
        key = event["customer_id"].encode("utf-8")

        producer.produce(
            topic=TOPIC,
            key=key,
            value=payload,
            on_delivery=_delivery_report,
        )
        produced += 1

        # Poll to trigger delivery callbacks and keep the internal queue healthy
        producer.poll(0)

        if produced % 100 == 0:
            log.info("Produced %d events (last customer: %s)", produced, event["customer_id"])

        # Honour the target rate regardless of produce() latency
        elapsed = time.monotonic() - start
        sleep_for = max(0.0, interval - elapsed)
        time.sleep(sleep_for)

    producer.flush(timeout=10)
    log.info("Done. Total events produced: %d", produced)


if __name__ == "__main__":
    bootstrap = os.getenv("KAFKA_BOOTSTRAP_SERVERS", "localhost:9092")
    run(bootstrap)
